switch out golangci-lint with more basic linting (#66)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,10 +32,15 @@ jobs:
         with:
           go-version: 1.19
 
-      - name: Run golangci-lint
-        uses: golangci/golangci-lint-action@v3
-        with:
-          version: v1.49
+      - name: Run go vet
+        run: go vet ./...
+
+      - name: Check gofmt passes
+        run: |
+          if [ -n "$(gofmt -l .)" ]; then
+            echo "gofmt failed, please run gofmt -w ."
+            exit 1
+          fi
 
       - name: Run shellcheck
         run: shellcheck **/*.sh
